#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
/*
 * 0 Layer: base
 *
 * .------------------------------------------.                   .------------------------------------------.
 * |  ` ~  |  1 ! |  2 @ |  3 # |  4 $ |  5 % |                   |  6 ^ |  7 & |  8 * |  9 ( |  0 ) |  - _  |
 * |-------+------+------+------+------+------|                   |------+------+------+------+------+-------|
 * |  tab  |  q   |  w   |  e   |  r   |  t   |                   |  y   |  u   |  i   |  o   |  p   |  = +  |
 * | hyper |      | shft | ctl  |  alt |  cmd |                   |      | cmd  | alt  | ctl  | shft |       |
 * |-------+------+------+------+------+------|                   |------+------+------+------+------+-------|
 * |  esc  |  a   |  s   |  d   |  f   |  g   |                   |  h   |  j   |  k   |  l   |  ; : |  ' "  |
 * |  meh  |      |      |      |      |      |                   |      |      |      |      |      |       |
 * '---------------------+------+------+------|--.             .--|------+------+------+------+------+-------'
 * |  shft |  z   |  x   |  c   |  v   |  b   |  |             |  |  n   |  m   |  , < |  . > |  / ? | shft  |
 * '-------+------+------+------+------+------+--.---.     .---.--+------+------+------+------+------+-------'
 *                |  mo1 |  mo2 |  meh | bksp |  spc |     |  ent | del  |  gui |  alt | ctl  |
 *                '------'--------------------'------'     '------'--------------------'------'
 */
    // ====== layer 0 ======
	[0] = LAYOUT(
     KC_GRV, KC_1, KC_2, KC_3, KC_4, KC_5,                            KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS,

     ALL_T(KC_TAB), KC_Q, MT(MOD_LSFT,KC_W), MT(MOD_LCTL,KC_E), MT(MOD_LALT,KC_R), MT(MOD_LGUI,KC_T),
                MT(MOD_RGUI, KC_Y), MT(MOD_RALT, KC_U), MT(MOD_RCTL,KC_I), MT(MOD_RSFT,KC_O), KC_P, KC_EQL,

     MEH_T(KC_ESC), KC_A, KC_S, KC_D, KC_F, KC_G,                      KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT,

     OSM(MOD_LSFT), KC_Z, KC_X, KC_C, KC_V, KC_B, XXXXXXX,    XXXXXXX, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, OSM(MOD_RSFT),

              MO(1), MO(2), KC_MEH, KC_BSPC, KC_SPC,           KC_ENT, KC_DEL, KC_RGUI, KC_RALT, KC_RCTL
    ),

/*
 * 1 Layer: num + symbols
 *
 * .------------------------------------------.                   .------------------------------------------.
 * |  TO 0 |  f1  |  f2  |  f3  |  f4  |  f5  |                   |  f6  |  f7  |  f8  |  f9  |  f10 |  f11  |
 * |-------+------+------+------+------+------|                   |------+------+------+------+------+-------|
 * |       |  {   |  }   |  €   |      |      |                   |  7   |  8   |  9   | Home |  End |  f12  |
 * |-------+------+------+------+------+------|                   |------+------+------+------+------+-------|
 * |       |  \   |  /   |  |   |      |      |                   |  4   |  5   |  6   | Home |  Up  | PgDn  |
 * '---------------------+------+------+------|--.             .--|------+------+------+------+------+-------'
 * |       |  [   |  ]   |      |      |      |  |             |  |  1   |  2   |  3   | PgUp | Down | Right |
 * '-------+------+------+------+------+------+--.---.     .---.--+------+------+------+------+------+-------'
 *                |      |      |      |      |      |     |      |  0   |  .   |      | Left |
 *                |      |      |      |      |      |     |      |  Del |      |      |      |
 *                '------'--------------------'------'     '------'--------------------'------'
 */
    // ====== layer 1 ======
	[1] = LAYOUT(
    TO(0), KC_F1, KC_F2, KC_F3, KC_F4, KC_F5,                       KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11,

    KC_TRNS, KC_LCBR, KC_RCBR, LALT(LSFT(KC_2)), KC_TRNS,KC_TRNS,   KC_7, KC_8, KC_9, KC_HOME, KC_END, KC_F12,

    KC_TRNS, KC_BSLS, KC_SLSH, KC_PIPE, KC_TRNS, KC_TRNS,           KC_4, KC_5, KC_6, KC_HOME, KC_UP, KC_PGDN,

  KC_TRNS, KC_LBRC, KC_RBRC, KC_TRNS , KC_TRNS, KC_TRNS, XXXXXXX,
                                                           XXXXXXX, KC_1, KC_2, KC_3, KC_PGUP, KC_DOWN, KC_RIGHT,

        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,     KC_TRNS, KC_0, KC_PDOT, KC_TRNS, KC_LEFT
    ),

/*
 * 2 Layer: arrows and system
 *
 * .------------------------------------------.                   .------------------------------------------.
 * |  TO 0 |      |      |      |      |      |                   | vol- | vol+ | mute | Ins  |      | reset |
 * |-------+------+------+------+------+------|                   |------+------+------+------+------+-------|
 * |       |      | ms 1 | ms up| ms 2 |      |                   |      |      |      | Home |  End | PgUp  |
 * |-------+------+------+------+------+------|                   |------+------+------+------+------+-------|
 * |       |      |ms lft|ms dn |ms rgt|      |                   | Left | Down |  Up  | Right|  Up  | PgDn  |
 * '---------------------+------+------+------|--.             .--|------+------+------+------+------+-------'
 * |       |      |      |      |      |      |  |             |  |      |      |      | PgUp | Down | Right |
 * '-------+------+------+------+------+------+--.---.     .---.--+------+------+------+------+------+-------'
 *                |      |      |      |      |      |     |      |  0   |  .   |      | Left |
 *                |      |      |      |      |      |     |      |  Del |      |      |      |
 *                '------'--------------------'------'     '------'--------------------'------'
 */
	[2] = LAYOUT(
    TO(0), KC_TRNS, KC_TRNS, BL_TOGG, BL_DOWN, BL_UP,          KC_KB_VOLUME_DOWN,KC_KB_VOLUME_UP,KC_KB_MUTE,KC_INS,KC_TRNS,QK_BOOT,

    KC_TRNS,KC_TRNS, KC_MS_BTN1,KC_MS_UP,KC_MS_BTN2,KC_TRNS,       KC_TRNS,KC_TRNS,KC_TRNS,KC_HOME,KC_END,KC_PGUP,

    KC_TRNS,KC_TRNS, KC_MS_LEFT,KC_MS_DOWN,KC_MS_RIGHT, KC_TRNS,   KC_LEFT,KC_DOWN,KC_UP,KC_RIGHT,KC_UP,KC_PGDN,

    KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS, XXXXXXX,
                                                           XXXXXXX, KC_TRNS,KC_TRNS,KC_TRNS, KC_PGUP, KC_DOWN, KC_RIGHT,

        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,     KC_TRNS, KC_0, KC_PDOT, KC_TRNS, KC_LEFT
    ),

//----------------------------------------------------------------------------------------------------------------------



	[3] = LAYOUT(
    // row 0 (6) left numbers
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    // row 0 (6) right
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,

    // row 1 (6) left qwe
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    // row 1 (6) right yui
        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,

    // row 2 (6) left asd
        XXXXXXX, RGB_TOG, RGB_HUI, RGB_SAI, RGB_VAI, XXXXXXX,
    // row 2 (6) right
        XXXXXXX, KC_VOLD, KC_MUTE, KC_VOLU, XXXXXXX, XXXXXXX,

    // row 3 (7) left zxc
        XXXXXXX, RGB_MOD, RGB_HUD, RGB_SAD, RGB_VAD, XXXXXXX, XXXXXXX,
    // row 3 (7) right
        XXXXXXX, XXXXXXX, KC_MPRV, KC_MPLY, KC_MNXT, XXXXXXX, XXXXXXX,

    // row 4 (5) left mods and space
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
    // row 4 (5) right enter and mods
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS)
};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)




